### ISSUE TITLE
What does the result look like?

### ISSUE THREAD

**Issue by FatherMcGruder** [cmayes/ofxstatement-betterment#1]
Does the plugin create different funds or just a series of accounts?

**Comment by cmayes** [comment]
It makes a series of accounts.  They're bank accounts rather than investment accounts, too; ofxstatement is written to process banking activity, and I haven't bothered learning enough about the OFX format to produce investment-specific OFX files.  The consolidated nature of the Betterment activity logs works pretty well for the banking credit/debit format, too; there's no fund-specific data, so there'd be nothing to split out, anyway.

**Comment by FatherMcGruder** [comment]
Thanks, Chris. Looking forward to trying it out.

Kurt

On April 13, 2016 8:57:26 PM EDT, Chris Mayes notifications@github.com wrote:

> It makes a series of accounts.  They're bank accounts rather than
> investment accounts, too; ofxstatement is written to process banking
> activity, and I haven't bothered learning enough about the OFX format
> to produce investment-specific OFX files.  The consolidated nature of
> the Betterment activity logs works pretty well for the banking
> credit/debit format, too; there's no fund-specific data, so there'd be
> nothing to split out, anyway.
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/cmayes/ofxstatement-betterment/issues/1#issuecomment-209704212

## 

Sent with K-9 Mail. GnuPG encryption available upon request.
